### ISSUE TITLE
Engine.io v2.0.0 crashes cloud9 on access

### ISSUE THREAD

**Issue by exsilium** [exsilium/cloud9#14]
Dep upgrade of engine.io v2.0.0 crashes Cloud9 when accessing the page with the following:

```javascript
/Users/exile/Projects/cloud9/node_modules/engine.io/lib/server.js:360
    self.ws.handleUpgrade(req, socket, head, function (conn) {
    
TypeError: Cannot read property 'handleUpgrade' of undefined
    at /Users/exile/Projects/cloud9/node_modules/engine.io/lib/server.js:360:12
    at Server.verify (/Users/exile/Projects/cloud9/node_modules/engine.io/lib/server.js:171:3)
    at Server.handleUpgrade (/Users/exile/Projects/cloud9/node_modules/engine.io/lib/server.js:349:8)
    at Server.<anonymous> (/Users/exile/Projects/cloud9/plugins-server/c9.smith.io/smith.io.js:229:16)
    at emitThree (events.js:121:20)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:409:14)
    at HTTPParser.onParserExecute (_http_server.js:377:5)
```

Found an open filed issue of a possible bug in engine.io: [socketio/engine.io#473](https://github.com/socketio/engine.io/issues/473) - Look into the proposed fix.

**Comment by exsilium** [comment]
Patch in the works: [socketio/engine.io#476](https://github.com/socketio/engine.io/pull/476)
