### ISSUE TITLE
[DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by exsilium** [exsilium/cloud9#31]
With node v8.0.0 the following Deprecation warning is given:

```
(node:25347) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:127:12)
    at Object.fs.close (fs.js:599:20)
    at /Users/exile/Projects/cloud9/node_modules/vfs-local/localfs.js:545:28
    at FSReqWrap.oncomplete (fs.js:135:15)
```

This impacts exsilium/vfs-local

**Comment by exsilium** [comment]
Fixed with exsilium/vfs-local#c5e6237a55859a07ab90cc259f31cd17dd6c7aed
