### ISSUE TITLE
Node 10.8, Ubuntu 16.04 - build failed

### ISSUE THREAD

**Issue by worldofswift** [exsilium/cloud9#49]
Having:
1. Ubuntu 16.04 on EC2
2. Node: 10, 9, 4
3. build-essentials, g++, g++-4.9
4. On the last phase of build we get:

```
> gnu-tools@0.0.9 postinstall /home/ubuntu/cloud9/cloud9/node_modules/gnu-tools
> node ./install.js

Creating directory  /home/ubuntu/cloud9/cloud9/node_modules/gnu-tools/bin
fs.js:135
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:135:11)
    at Object.mkdir (fs.js:711:16)
    at main (/home/ubuntu/cloud9/cloud9/node_modules/gnu-tools/install.js:28:12)
    at Object.<anonymous> (/home/ubuntu/cloud9/cloud9/node_modules/gnu-tools/install.js:228:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

What should I do to overcome it?
Or can everyone show some box with successfully installed cloud 9 (packages, version numbers).

**Comment by exsilium** [comment]
Reproduced with `v10.8.0`. Current workaround is to drop to node `v8.11.3`

`(node:30986) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

**Comment by exsilium** [comment]
@worldofswift , if you have time it would be great to get feedback if the reported issue is resolved using `development` branch. Thanks and Cheers!

**Comment by worldofswift** [comment]
@exsilium , sorry but I get the same problem. No, after the build phase on the launching stage.

**Comment by exsilium** [comment]
Maybe comparison with Travis-CI job would help to indicate where the issue is: https://travis-ci.org/exsilium/cloud9/jobs/427164563

The original `gnu-tools` that caused the issue should not be pulled in nor built so should not trigger the failure, if it still doesn't work, there should be additional log output. Make sure you are on `development` branch and that you have pulled all the commits.
